Help_GTextDraw = TextDrawCreate(320.999969, 406.933349, "HAME \"ALT\"  COPA");
TextDrawLetterSize(Help_GTextDraw, 0.374998, 1.359406);
TextDrawAlignment(Help_GTextDraw, 2);
TextDrawColor(Help_GTextDraw, -1);
TextDrawSetShadow(Help_GTextDraw, 0);
TextDrawSetOutline(Help_GTextDraw, 1);
TextDrawBackgroundColor(Help_GTextDraw, 51);
TextDrawFont(Help_GTextDraw, 1);
TextDrawSetProportional(Help_GTextDraw, 1);