Count_PTextDraw[playerid] = CreatePlayerTextDraw(playerid, 576.333374, 149.333312, "COPAHO: 0");
PlayerTextDrawLetterSize(playerid, Count_PTextDraw[playerid], 0.364332, 1.496296);
PlayerTextDrawAlignment(playerid, Count_PTextDraw[playerid], 2);
PlayerTextDrawColor(playerid, Count_PTextDraw[playerid], -1);
PlayerTextDrawSetShadow(playerid, Count_PTextDraw[playerid], 0);
PlayerTextDrawSetOutline(playerid, Count_PTextDraw[playerid], 1);
PlayerTextDrawBackgroundColor(playerid, Count_PTextDraw[playerid], 51);
PlayerTextDrawFont(playerid, Count_PTextDraw[playerid], 2);
PlayerTextDrawSetProportional(playerid, Count_PTextDraw[playerid], 1);