Help_TextDraw = TextDrawCreate(320.999969, 406.933349, "HAME \"ALT\"  COPA");
TextDrawLetterSize(Help_TextDraw, 0.374998, 1.359406);
TextDrawAlignment(Help_TextDraw, 2);
TextDrawColor(Help_TextDraw, -1);
TextDrawSetShadow(Help_TextDraw, 0);
TextDrawSetOutline(Help_TextDraw, 1);
TextDrawBackgroundColor(Help_TextDraw, 51);
TextDrawFont(Help_TextDraw, 1);
TextDrawSetProportional(Help_TextDraw, 1);